compile without generating *.d.ts (#71)
* ignoring directory idea/

* Resolve issue #69
reconnectIfNotNormalClose ignores normal close #69

* script for compiling with no *.d.ts generation

This will avoid the compilation error below:
error TS5055: Cannot write file '.../angular2-websocket.d.ts' because it would overwrite input file.